# Generated by Django 6.0.2 on 2026-03-06 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner_url', models.URLField(blank=True, null=True, verbose_name='URL do Banner')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link da Publicação')),
                ('value_publi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Publicação')),
                ('crop_x', models.IntegerField(blank=True, null=True, verbose_name='Eixo x')),
                ('crop_y', models.IntegerField(blank=True, null=True, verbose_name='Eixo y')),
                ('crop_width', models.IntegerField(blank=True, null=True, verbose_name='Corte Largura')),
                ('crop_height', models.IntegerField(blank=True, null=True, verbose_name='Corte Altura')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
