# Generated by Django 6.0.2 on 2026-03-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='banner',
            name='properties',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Propiedades'),
        ),
    ]
