# Generated by Django 6.0.2 on 2026-03-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('plate', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Placa')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro'), ('bicicleta', 'Bicicleta'), ('van', 'Van'), ('outro', 'Outro')], default='moto', max_length=20, verbose_name='Tipo de Veículo')),
                ('color', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cor do Veículo')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Avatar URL')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Tota de entregas')),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='Conta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to=settings.AUTH_USER_MODEL, verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
