# Generated by Django 6.0.2 on 2026-02-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'verbose_name': 'Entregador', 'verbose_name_plural': 'Entregadores'},
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to=settings.AUTH_USER_MODEL, verbose_name='Entregador'),
        ),
    ]
