# Generated by Django 6.0.2 on 2026-03-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_user'),
        ('delivery', '0002_alter_deliveryman_options_alter_deliveryman_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entregador', 'verbose_name_plural': 'Entregadores'},
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='Conta'),
        ),
    ]
