# Generated by Django 6.0.2 on 2026-02-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='number',
            new_name='house_number',
        ),
    ]
