# Generated by Django 6.0.2 on 2026-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Moedas de troca'),
        ),
    ]
