# Generated by Django 6.0.2 on 2026-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_number_customers_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da casa'),
        ),
    ]
