# Generated by Django 6.0.2 on 2026-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da casa'),
        ),
    ]
