# Generated by Django 6.0.2 on 2026-03-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do cliente')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Longitude')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Número da casa')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pago com')),
                ('rate_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código')),
                ('status', models.BooleanField(default=False, verbose_name='Entregue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('itens', models.JSONField(blank=True, null=True, verbose_name='Lista de Itens')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Cliente')),
                ('delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.deliveryman', verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
