# Generated by Django 6.0.2 on 2026-02-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.JSONField(blank=True, null=True, verbose_name='Itens')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('rate_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hour', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customers', verbose_name='Cliente')),
            ],
        ),
    ]
