# Generated by Django 6.0.2 on 2026-02-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_remove_order_delivery_manid_order_delivery_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco')),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True, verbose_name='Pago com')),
                ('rate_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('status', models.BooleanField(default=False)),
                ('collaborator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colaborador')),
                ('observation', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='Conta')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
