# Generated by Django 6.0.2 on 2026-03-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Pedido'),
        ),
    ]
