# Generated by Django 6.0.2 on 2026-03-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('description', models.TextField(default='Categoria sem descrição', max_length=320, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(db_index=True, max_length=50, verbose_name='Categoria')),
                ('description', models.TextField(default='Produto sem descrição', max_length=320, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('crop_x', models.IntegerField(blank=True, null=True, verbose_name='Eixo x')),
                ('crop_y', models.IntegerField(blank=True, null=True, verbose_name='Eixo y')),
                ('crop_width', models.IntegerField(blank=True, null=True, verbose_name='Corte Largura')),
                ('crop_height', models.IntegerField(blank=True, null=True, verbose_name='Corte Altura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
