# Generated by Django 6.0.2 on 2026-03-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_remove_product_id_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
